######################################################################
#
# File name : tb_ov5640_gray_wave.do
# Created on: Wed Sep 14 14:54:34 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
