######################################################################
#
# File name : tb_ov5640_gray_compile.do
# Created on: Wed Sep 14 15:56:17 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog  -incr -mfcu -work xil_defaultlib  "+incdir+../../../../ov5640_gesture.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../ov5640_gesture.gen/sources_1/bd/system/ipshared/5765/hdl" "+incdir+../../../../ov5640_gesture.gen/sources_1/bd/system/ipshared/fc4b/hdl" "+incdir+E:/FPGA_xilinx_vivado_newversion/Vivado/2022.1/data/xilinx_vip/include" \
"../../../../rtl/get_gesture_area.v" \
"../../../../rtl/ov5640_capture_data.v" \
"../../../../rtl/rgb2ycbcr.v" \
"../../../../rtl/tb_ov5640_gray.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

